/*
**	Command & Conquer Red Alert(tm)
**	Copyright 2025 Electronic Arts Inc.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
**
**	This program is distributed in the hope that it will be useful,
**	but WITHOUT ANY WARRANTY; without even the implied warranty of
**	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**	GNU General Public License for more details.
**
**	You should have received a copy of the GNU General Public License
**	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef VQMALL_H
#define VQMALL_H
/****************************************************************************
*
*        C O N F I D E N T I A L -- W E S T W O O D  S T U D I O S
*
*----------------------------------------------------------------------------
*
* FILE
*     all.h
*
* DESCRIPTION
*     All VQMisc32 library definitions. (32-Bit protected mode)
*
* PROGRAMMER
*     Denzil E. Long, Jr.
*
* DATE
*     July 5, 1995
*
****************************************************************************/

#include <vqm32\IFF.H>
#include <vqm32\MONO.H>
#include <vqm32\PORTIO.H>
#include <vqm32\PROFILE.H>
#include <vqm32\TARGA.H>
#include <vqm32\COMPRESS.H>
#include <vqm32\VIDEO.H>
#include <vqm32\PALETTE.H>
#include <vqm32\VESAVID.H>
#include <vqm32\VESABLIT.H>
#include <vqm32\GRAPHICS.H>
#include <vqm32\MIXFILE.H>
#include <vqm32\CRC.H>
#include <vqm32\HUFFMAN.H>
#include <vqm32\mem.h>

#endif /* VQMALL_H */

