/*
**	Command & Conquer Red Alert(tm)
**	Copyright 2025 Electronic Arts Inc.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
**
**	This program is distributed in the hope that it will be useful,
**	but WITHOUT ANY WARRANTY; without even the implied warranty of
**	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**	GNU General Public License for more details.
**
**	You should have received a copy of the GNU General Public License
**	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef VQMALL_H
#define VQMALL_H
/****************************************************************************
*
*        C O N F I D E N T I A L -- W E S T W O O D  S T U D I O S
*
*----------------------------------------------------------------------------
*
* FILE
*     all.h
*
* DESCRIPTION
*     All VQMisc32 library definitions. (32-Bit protected mode)
*
* PROGRAMMER
*     Denzil E. Long, Jr.
*
* DATE
*     July 5, 1995
*
****************************************************************************/

#include <VQM32/IFF.H>
#include <VQM32/MONO.H>
#include <VQM32/PORTIO.H>
#include <VQM32/PROFILE.H>
#include <VQM32/TARGA.H>
#include <VQM32/COMPRESS.H>
#include <VQM32/VIDEO.H>
#include <VQM32/PALETTE.H>
#include <VQM32/VESAVID.H>
#include <VQM32/VESABLIT.H>
#include <VQM32/GRAPHICS.H>
#include <VQM32/MIXFILE.H>
#include <VQM32/CRC.H>
#include <VQM32/HUFFMAN.H>
#include <VQM32/MEM.H>

#endif /* VQMALL_H */
